name: Bicep Deploy

on:
  push:
    branches:
      - main
    paths:
      - "GUITemplate2.0"
      - ".github/workflows/bicep-deploy.yml"
  pull_request:
    types: [opened, synchronize, reopened ]
    branches:
      - main
    paths:
      - "GUITemplate2.0"
      - ".github/workflows/bicep-deploy.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy-with-bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./GUITemplate2.0/template.bicep
          parameters: ./GUITemplate2.0/parameters.json
          failOnStdErr: false